In [21]:
using LinearAlgebra
using SparseArrays
using Arpack

In [2]:
σˣ = [0 1; 1 0];
σʸ = [0 -im; im 0];
σᶻ = [1 0; 0 -1];

In [3]:
u0 = [0 0 1 0; 0 0 0 1; 1 0 0 0; 0 1 0 0];
u1 = [0 0 0 -im; 0 0 -im 0; 0 im 0 0; im 0 0 0];
u2 = [0 0 0 -1; 0 0 1 0; 0 1 0 0; -1 0 0 0];
u3 = [0 0 -im 0; 0 0 0 im; im 0 0 0; 0 -im 0 0];

In [4]:
dagger(T) = conj(transpose(T))

dagger (generic function with 1 method)

In [5]:
⊗(x,y) = kron(x,y)

⊗ (generic function with 1 method)

In [18]:
u00 = [u0+im*u3 im*u1+u2; im*u1-u2 u0-im*u3];
u00_dag = [u0-im*u3 -im*u1-u2; -im*u1+u2 u0+im*u3];

In [19]:
"""
On our lattice we have just four site
!! But without considering any boundry condition
We just examine our codes
"""
H0 = ⊗(⊗(u00,u00),⊗(u00_dag,u00_dag)) + ⊗(⊗(u00,u00),⊗(u00_dag,u00_dag))

H0

In [7]:
u11 = u0+im*u3;
u12 = im*u1+u2;
u21 = im*u1-u2;
u22 = u0-im*u3;

In [8]:
u11_dag = u0-im*u3;
u12_dag = -im*u1-u2;
u21_dag = -im*u1+u2;
u22_dag = u0+im*u3;

In [9]:
"""
Tr(U_sq)
"""
H_U_sq = ⊗(⊗(u11,u11),⊗(u11_dag,u11_dag)) +  ⊗(⊗(u11,u11),⊗(u12_dag,u21_dag)) 
        +  ⊗(⊗(u12,u21),⊗(u11_dag,u11_dag)) +  ⊗(⊗(u12,u21),⊗(u12_dag,u21_dag))
        +  ⊗(⊗(u11,u12),⊗(u21_dag,u11_dag)) +  ⊗(⊗(u11,u12),⊗(u22_dag,u21_dag))
        +  ⊗(⊗(u12,u22),⊗(u21_dag,u11_dag)) +  ⊗(⊗(u12,u22),⊗(u22_dag,u21_dag))
        +  ⊗(⊗(u21,u11),⊗(u11_dag,u12_dag)) +  ⊗(⊗(u21,u11),⊗(u12_dag,u22_dag)) 
        +  ⊗(⊗(u22,u21),⊗(u11_dag,u12_dag)) +  ⊗(⊗(u22,u21),⊗(u12_dag,u22_dag)) 
        +  ⊗(⊗(u21,u12),⊗(u21_dag,u12_dag)) +  ⊗(⊗(u21,u12),⊗(u22_dag,u22_dag)) 
        +  ⊗(⊗(u22,u22),⊗(u21_dag,u12_dag)) +  ⊗(⊗(u22,u22),⊗(u22_dag,u22_dag))
        

256×256 Matrix{Complex{Int64}}:
 0+0im  0+0im  0+0im  0+0im  0+0im  …  0+0im  0+0im  0+0im  0+0im  0+0im
 0+0im  0+0im  0+0im  0+0im  0+0im     0+0im  0+0im  0+0im  0+0im  0+0im
 0+0im  0+0im  0+0im  0+0im  0+0im     0+0im  0+0im  0+0im  0+0im  0+0im
 0+0im  0+0im  0+0im  0+0im  0+0im     0+0im  0+0im  0+0im  0+0im  0+0im
 0+0im  0+0im  0+0im  0+0im  0+0im     0+0im  0+0im  0+0im  0+0im  0+0im
 0+0im  0+0im  0+0im  0+0im  0+0im  …  0+0im  0+0im  0+0im  0+0im  0+0im
 0+0im  0+0im  0+0im  0+0im  0+0im     0+0im  0+0im  0+0im  0+0im  0+0im
 0+0im  0+0im  0+0im  0+0im  0+0im     0+0im  0+0im  0+0im  0+0im  0+0im
 0+0im  0+0im  0+0im  0+0im  0+0im     0+0im  0+0im  0+0im  0+0im  0+0im
 0+0im  0+0im  0+0im  0+0im  0+0im     0+0im  0+0im  0+0im  0+0im  0+0im
 0+0im  0+0im  0+0im  0+0im  0+0im  …  0+0im  0+0im  0+0im  0+0im  0+0im
 0+0im  0+0im  0+0im  0+0im  0+0im     0+0im  0+0im  0+0im  0+0im  0+0im
 0+0im  0+0im  0+0im  0+0im  0+0im     0+0im  0+0im  0+0im  0+0im  0+0im
  ⋮                

In [10]:
"""
Tr(U_sq_dag)
"""
H_U_sq_dag =  ⊗(⊗(u11_dag,u11_dag),⊗(u11,u11)) + ⊗(⊗(u21_dag,u12_dag),⊗(u11,u11)) 
            + ⊗(⊗(u11_dag,u11_dag),⊗(u21,u12)) + ⊗(⊗(u21_dag,u12_dag),⊗(u21,u12))
            + ⊗(⊗(u11_dag,u21_dag),⊗(u12,u11)) + ⊗(⊗(u21_dag,u22_dag),⊗(u12,u11))
            + ⊗(⊗(u11_dag,u21_dag),⊗(u22,u12)) + ⊗(⊗(u21_dag,u22_dag),⊗(u22,u12))
            + ⊗(⊗(u12_dag,u11_dag),⊗(u11,u21)) + ⊗(⊗(u22_dag,u12_dag),⊗(u11,u21))
            + ⊗(⊗(u12_dag,u11_dag),⊗(u21,u22)) + ⊗(⊗(u22_dag,u12_dag),⊗(u21,u22))
            + ⊗(⊗(u12_dag,u21_dag),⊗(u12,u21)) + ⊗(⊗(u22_dag,u22_dag),⊗(u12,u21)) 
            + ⊗(⊗(u12_dag,u21_dag),⊗(u22,u22)) + ⊗(⊗(u22_dag,u22_dag),⊗(u22,u22)) 

256×256 Matrix{Complex{Int64}}:
 0+0im  0+0im  0+0im  0+0im  0+0im  …  0+0im  0+0im  0+0im  0+0im  0+0im
 0+0im  0+0im  0+0im  0+0im  0+0im     0+0im  0+0im  0+0im  0+0im  0+0im
 0+0im  0+0im  0+0im  0+0im  0+0im     0+0im  0+0im  0+0im  0+0im  0+0im
 0+0im  0+0im  0+0im  0+0im  0+0im     0+0im  0+0im  0+0im  0+0im  0+0im
 0+0im  0+0im  0+0im  0+0im  0+0im     0+0im  0+0im  0+0im  0+0im  0+0im
 0+0im  0+0im  0+0im  0+0im  0+0im  …  0+0im  0+0im  0+0im  0+0im  0+0im
 0+0im  0+0im  0+0im  0+0im  0+0im     0+0im  0+0im  0+0im  0+0im  0+0im
 0+0im  0+0im  0+0im  0+0im  0+0im     0+0im  0+0im  0+0im  0+0im  0+0im
 0+0im  0+0im  0+0im  0+0im  0+0im     0+0im  0+0im  0+0im  0+0im  0+0im
 0+0im  0+0im  0+0im  0+0im  0+0im     0+0im  0+0im  0+0im  0+0im  0+0im
 0+0im  0+0im  0+0im  0+0im  0+0im  …  0+0im  0+0im  0+0im  0+0im  0+0im
 0+0im  0+0im  0+0im  0+0im  0+0im     0+0im  0+0im  0+0im  0+0im  0+0im
 0+0im  0+0im  0+0im  0+0im  0+0im     0+0im  0+0im  0+0im  0+0im  0+0im
  ⋮                

In [11]:
H = H_U_sq + H_U_sq_dag

256×256 Matrix{Complex{Int64}}:
 0+0im  0+0im  0+0im  0+0im  0+0im  …  0+0im  0+0im  0+0im  0+0im  0+0im
 0+0im  0+0im  0+0im  0+0im  0+0im     0+0im  0+0im  0+0im  0+0im  0+0im
 0+0im  0+0im  0+0im  0+0im  0+0im     0+0im  0+0im  0+0im  0+0im  0+0im
 0+0im  0+0im  0+0im  0+0im  0+0im     0+0im  0+0im  0+0im  0+0im  0+0im
 0+0im  0+0im  0+0im  0+0im  0+0im     0+0im  0+0im  0+0im  0+0im  0+0im
 0+0im  0+0im  0+0im  0+0im  0+0im  …  0+0im  0+0im  0+0im  0+0im  0+0im
 0+0im  0+0im  0+0im  0+0im  0+0im     0+0im  0+0im  0+0im  0+0im  0+0im
 0+0im  0+0im  0+0im  0+0im  0+0im     0+0im  0+0im  0+0im  0+0im  0+0im
 0+0im  0+0im  0+0im  0+0im  0+0im     0+0im  0+0im  0+0im  0+0im  0+0im
 0+0im  0+0im  0+0im  0+0im  0+0im     0+0im  0+0im  0+0im  0+0im  0+0im
 0+0im  0+0im  0+0im  0+0im  0+0im  …  0+0im  0+0im  0+0im  0+0im  0+0im
 0+0im  0+0im  0+0im  0+0im  0+0im     0+0im  0+0im  0+0im  0+0im  0+0im
 0+0im  0+0im  0+0im  0+0im  0+0im     0+0im  0+0im  0+0im  0+0im  0+0im
  ⋮                

In [13]:
sparse(H)

256×256 SparseMatrixCSC{Complex{Int64}, Int64} with 64 stored entries:
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡀⠴⠄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠆⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠰⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⡔⠋⠀⠀⠀⠀⠀⢀⠁⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠰⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡠⠀⠀⠀⠀⠀⠀⠂⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠰⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠆⠀⠀⠀⠀⠀⠀⠰⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠠⠀⠀⠀⠀⠀⠀⠊⠀⠀⠀⠀⠀⠀⠐⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠆⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⠐⠂⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢐⠆⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀

In [14]:
H_sparse = sparse(H)

256×256 SparseMatrixCSC{Complex{Int64}, Int64} with 64 stored entries:
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡀⠴⠄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠆⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠰⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⡔⠋⠀⠀⠀⠀⠀⢀⠁⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠰⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡠⠀⠀⠀⠀⠀⠀⠂⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠰⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠆⠀⠀⠀⠀⠀⠀⠰⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠠⠀⠀⠀⠀⠀⠀⠊⠀⠀⠀⠀⠀⠀⠐⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠆⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⠐⠂⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢐⠆⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀

In [15]:
H_sparse

256×256 SparseMatrixCSC{Complex{Int64}, Int64} with 64 stored entries:
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡀⠴⠄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠆⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠰⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⡔⠋⠀⠀⠀⠀⠀⢀⠁⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠰⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡠⠀⠀⠀⠀⠀⠀⠂⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠰⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠆⠀⠀⠀⠀⠀⠀⠰⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠠⠀⠀⠀⠀⠀⠀⠊⠀⠀⠀⠀⠀⠀⠐⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠆⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⠄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⠐⠂⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢐⠆⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀

In [22]:
eigenval, eigenvec = eigs(H_sparse);

In [23]:
eigenval 

6-element Vector{ComplexF64}:
   16.00000000000003 - 1.3322676295501878e-15im
  16.000000000000018 - 6.626643678231403e-16im
  16.000000000000018 + 1.5959455978986625e-16im
  -16.00000000000001 + 5.551115123125783e-16im
 -16.000000000000004 + 9.974659986866641e-17im
               -16.0 + 1.1832263763679883e-15im

In [26]:
length(eigenvec)

1536

In [37]:
size(eigenvec)

(256, 6)

In [45]:
eigenvec[1:6]

6-element Vector{ComplexF64}:
 -1.4591557300322986e-17 + 3.1108953000694786e-17im
 -1.2911400985099488e-17 + 6.5506979720802854e-18im
 -1.2944299408750096e-17 - 9.792535360391392e-18im
   1.370294092388348e-17 - 2.9141112523240656e-17im
  -6.923149905452563e-18 - 7.165106121220642e-17im
    -0.01607671450374713 + 0.020049954368231718im

In [46]:
issparse(H_sparse)

true

In [73]:
eigs(H_sparse,nev = 20,which = :SR)[1]

20-element Vector{ComplexF64}:
     -16.00000000000005 - 2.3326401826124836e-15im
    -16.000000000000043 - 3.1786617565739557e-15im
    -16.000000000000036 + 9.098341353166155e-16im
    -16.000000000000036 - 1.3440130336630781e-15im
    -16.000000000000032 - 2.602249542492881e-15im
    -16.000000000000025 - 1.3728928935843218e-16im
    -16.000000000000025 + 5.260574212838918e-17im
    -16.000000000000018 + 3.521725113862711e-15im
    -16.000000000000018 + 4.999999541254113e-15im
     -16.00000000000001 - 4.246662660581926e-15im
    -16.000000000000007 + 2.121919907392798e-15im
    -16.000000000000004 - 2.322871559646758e-15im
    -16.000000000000004 - 1.3661449634982408e-15im
    -15.999999999999996 + 4.572510868106485e-16im
     -15.99999999999999 - 2.077162954299775e-15im
    -15.999999999999984 - 4.181771526769446e-15im
 -1.4225413843488643e-8 + 2.9317838841882986e-9im
 -1.2148449251928126e-8 + 3.665087231333861e-11im
 -1.1960160628154327e-8 + 4.471336869306597e-9im
 -1.03914614824

In [58]:
?eigs

search: eigs eigvecs eigvals eigvals! leading_ones leading_zeros eigen eigmin



```
eigs(A; nev=6, ncv=max(20,2*nev+1), which=:LM, tol=0.0, maxiter=300, sigma=nothing, ritzvec=true, explicittransform=:auto, v0=zeros((0,)), check=0) -> (d,[v,],nconv,niter,nmult,resid)
```

Computes eigenvalues `d` of `A` using implicitly restarted Lanczos or Arnoldi iterations for real symmetric or general nonsymmetric matrices respectively. See [the manual](@ref man-eigs) for more information.

`eigs` returns the `nev` requested eigenvalues in `d`, the corresponding Ritz vectors `v` (only if `ritzvec=true`), the number of converged eigenvalues `nconv`, the number of iterations `niter` and the number of matrix vector multiplications `nmult`, as well as the final residual vector `resid`. The parameter `explicittransform` takes the values `:auto`, `:none` or `:shiftinvert`, specifying if shift and invert should be explicitly invoked in julia code.

When `check = 0`, an error is thrown if maximum number of iterations taken (`info = 1`). This usually means all possible eigenvalues has been found according to ARPACK manual. When `check = 1`, return currently converged eigenvalues when `info = 1`. And a `@warn` will given. When `check = 2`, return currently converged eigenvalues when `info = 1`.

# Examples

```jldoctest
julia> using LinearAlgebra, Arpack

julia> A = Diagonal(1:4);

julia> λ, ϕ = eigs(A, nev = 2);

julia> λ
2-element Array{Float64,1}:
 3.9999999999999996
 3.000000000000001
```

---

```
eigs(A, B; nev=6, ncv=max(20,2*nev+1), which=:LM, tol=0.0, maxiter=300, sigma=nothing, ritzvec=true, v0=zeros((0,)), check=0) -> (d,[v,],nconv,niter,nmult,resid)
```

Computes generalized eigenvalues `d` of `A` and `B` using implicitly restarted Lanczos or Arnoldi iterations for real symmetric or general nonsymmetric matrices respectively. See [the manual](@ref man-eigsgen) for more information.

When `check = 0`, an error is thrown if maximum number of iterations taken (`info = 1`). This usually means all possible eigenvalues has been found according to ARPACK manual. When `check = 1`, return currently converged eigenvalues when `info = 1`. And a `@warn` will given. When `check = 2`, return currently converged eigenvalues when `info = 1`.
